const EstadoConversa = {
  BOAS_VINDAS: 'BOAS_VINDAS',
  ACOLHIMENTO_ORIENTACAO: 'ACOLHIMENTO_ORIENTACAO',
  SOLICITAR_CPF: 'SOLICITAR_CPF',
  TORNAR_VOLUNTARIO: 'TORNAR_VOLUNTARIO',
  ATENDIMENTO_HUMANO: 'ATENDIMENTO_HUMANO',
};

module.exports = EstadoConversa;
